name: googlemap
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  geocoder: ^0.2.1
  geolocator: ^5.3.0
  firebase_database: ^3.1.5
  google_maps_utils: ^1.2.1+1
  google_maps_flutter: ^0.5.24+1
  google_maps_webservice: ^0.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
